= Técnica y trabajo
Hector Rodriguez
:doctype: article
:pdf-page-size: A4
:title-page:
:pagenums:

== Quehacer

- [x] Introducción
- [-] Div. Tecnica
- [x] Div. Social
- [ ] Org. Soc. Cult.
- [-] Organigrama
- [ ] Diag. Procesos.
- [ ] Conclusion ?

== Introducción

La pasantía se trata sobre Ascensores Liftschitz, una compañía familiar de ascensores fundada en 1984.
A pesar de ser de ascensores, tienen una sección de desarrollo de software de forma freelance.

Mis tutores son Mariano y Maruo.  Mariano sabe sobre tecnología, pero no tiene
un rol de programación.  Tiene más un rol de gestión, y creo que es de recursos humanos.  Mauro,
por otro lado, sí tiene un rol de programación.

Mi rol dentro de la compañía es el de programador full stack; Hago trabajos tanto de front-end
como de back-end.  Hago la pasantía de forma remota de lunes a viernes, de 9 a 13.

== División técnica del trabajo

Hay una división de trabajo, en la forma de desarrolladores de front-end y back-end; Los desarrolladores
de front-end se encargan de desarrollar páginas web, mientras que los desarrolladores de back-end se encargan
de desarrollar el servidor que va a utilizar esta página.  Nuestros tutores actuan como project managers, siendo
su trabajo el de coordinar a los pasantes, y darnos tareas a realizar.

La empresa, además, cuenta con otras áreas con las que no soy del todo familiar; Todo lo que tiene que ver con
la instalación de ascensores, la logística detras de esto, finanzas, recursos humanos, etc.  Pero ahí hay otra
clara divisón de trabajo.

== División social del trabajo

// TODO: Mejor redacción

.Jerarquía
Nuestros tutores son la máxima jerarquía con la que interactuamos, y ellos toman
el rol de project managers.  Nos dan tareas a realizar, y hacemos un seguimiento
semanal sobre el progreso de las tareas que nos dieron.

.Roles y tareas
Estas tareas que nos dan están divididas en dos ámbitos, front-end y back-end.
En el fron-end, se realiza el diseño y desarrollo de páginas web, tomando
en cuenta los requerimientos y consideraciones particulares de cada cliente.
Por ejemplo, desarrollamos varias propuestas de páginas web para un estudio
contable que no contaba con una, y en el diseño se tuvo que tomar en cuenta
cosas como la tipografía, la paleta de colores, e imágenes apropiadas
específicamente para un estudio contable.
En el back-end, se realiza el desarrollo de los servidores que van a utilizar
las páginas web, y se sube este a un servidor FTP para poder acceder a la
página desarrollada desde el sitio web de la empresa.  Se encargan de programar
endpoints del servidor con el que se comunica el front-end y el navegador.
Por ejemplo, tuve que hacer un endpoint llamado algo como `enviarMail` en el
servidor.  El font-end hacía un pedido de HTTP a este endpoint, enviando
ciertos datos de un formulario en una de las páginas web, y el servidor
utilizaba el protocolo SMTP para enviar los datos por mail.
Además, aunque no me tocó hacerlo durante la pasantía, el back-end trabaja con
bases de datos; Creándolas, gestionandolas, y conectándolas con el servidor.

// TODO: Mejor redacción

.Especialización
Hay una división de especialización entre front-end y back-end.  Para estas
dos especializaciones, se necesita conocimiento sobre la computación, aunque hay
ámbitos donde con una capacitación es suficiente, por ejemplo: en el caso de
frameworks y librerías para el front-end, hay muchos cursos de capacitación, y no se
necesita un título para utilizar dichas tecnologías.  En el caso del back-end, diría
yo que el conocimiento sobre la computación es mucho más necesario.  Aquí, la
capacitación sobre temas como manejo de base de servidores, bases de datos, y sobre
seguridad es mucho más importante.

Aun así, se necesita conocimiento sobre la computación para ambos cargos.  Siendo
más específico, un titulo técnico o terciario sobre programación o computación es necesario
para trabajar en estos roles.  Además, dependiendo del trabajo, se necesita capacitación
adicional en temas aún más específicos que corresponden al carácter de la actividad realizada.

.Roles de género
En cuanto a roles de género, el equipo desarrollo de la empresa parece tener más hombres.

.Notas
* Jerarquia
* Desarollas en Roles y tareas
* Roles de genero
* Especialización

== Tecnologías

Para el front-end de los proyectos, se utiliza HTML, CSS, y Javascript
principalmente.  También se utilizan frameworks como Bootstrap, para
embellecer las páginas web y hacer que sean responsivas, y librerías
de javascript como jQuery, para facilitar la manipulación de elementos
en la página web.  Otra librería que utilizan es React, esta la utilizan
para crear interfaces con componentes reutilizables.  Se utilizan multiples
navegadores web para confirmar que las páginas web se vean bien en distintos
navegadores, principalmente se testea en Chrome, Firefox, y Microsofr Edge.

Para el back-end de los proyectos, se utiliza C# y el framework .NET.
El entorno de desarrollo integrado que utilizan para desarrollar el backend
es Visual Studio.  El código compilado se sube a un servidor FTP, y el cliente
FTP recomendado es FileZilla.  Este servidor con FTP utiliza la tecnología
IIS de Microsoft.  Se utiliza ASP.NET como framework para desarrollo de
servidores web. Se utiliza MySQL para las bases de datos.

Para el control de código fuente, se utiliza git, y github como plataforma
de hosteo.

.Ideas
* Framework .NET
* Visual studio
* SQL
* HTML, CSS, JS, React

== Organización social y cultural

La empresa promueve la comunicación y el trabajo en equipo. [...], promueve libertades
individuales, como la flexibilidad del horario laboral, y [...](no vigilan tanto).

[...] en el entorno laboral, se promueve mucho la colaboración y ayuda entre pasantes.  Además, se utilizan
herramientas de desarrollo colaborativo, como git.

.Ideas
* Las sesiones son tranquilas
* Dan mucha libertad
* Son muy abiertos y amables
* Horario flexible

== Organigrama

Lorem ipsum

Como no tengo mucho contacto con el resto de la compañía, no se mucho
de cómo esta estructurada.

.Departamentos
* Gerencia general
* RRHH
* Departamento de programación
* Departamento de contablilidad
+
_Recuerdo que me habían mencionado que una alumna de sexto del año pasado_
_había hecho una pasantía de contadora aquí, así que deben tender un departamento_
_de contabilidad._

graphviz::organigrama.dot[format=svg]

== Diagrama de procesos

graphviz::procesos.dot[format=svg]

== Conclusión

Lorem ipsum
